#' Heatmap
#'
#' This function plots heatmaps dos metabólitos.
#' @export
#' @param myDir Path to the directory of work.
#' @param example Only for software testing. No pictures will be created.
#' @param metadata A matrix or data.frame with metadata information about samples. Include, at least 'sample' and 'file' columns with name of sample and its path, respectively. More information can be added in new columns, such as 'group', 'class', 'biorep' and 'tecrep'.
#' @param n A normalized matrix generated by 'PipMet::normalize()'
#' @param colors A list with colors generated from 'read_data()'.
#' @param sample_names Character. Name of metadata column to name the samples. Default to NULL. If NULL, the user will be asked.
#' @param replicate Character or Logical. If FALSE, there is no replicate informations in the metadata table. Otherwise, inform the name in the metadata column containing replicate information. If NULL, the user will be asked. Default to NULL.
#' @param pic_extension Character. Pictures format to generate. Supported = '.tiff', '.png'. Default to c('.tiff', '.png').
#' @return None.
#' @importFrom svDialogs dlgInput dlg_message dlg_list
#' @importFrom grDevices dev.off pdf png tiff
#' @importFrom graphics boxplot grid legend par text
#' @importFrom methods as new
#' @importFrom stats cor sd t.test var
#' @importFrom utils read.csv write.csv write.table
#' @importFrom pheatmap pheatmap
#' @examples
#' \donttest{
#' \dontrun{
#' load(system.file("extdata", "n.RData", package = "PipMet"))
#' load(system.file("extdata", "metadata.RData", package = "PipMet"))
#' load(system.file("extdata", "colors.RData", package = "PipMet"))
#' heatmap(n, metadata, colors = colors, replicate = "group", example = TRUE)
#' }
#' }
heatmap <- function(n, metadata, myDir, colors, pic_extension = c(".tiff", ".png"),
                    replicate = NULL, sample_names = NULL, example = FALSE) {
  # group <- dlg_list(names(metadata), multiple = FALSE, title = 'Specify
  # groups:')$res subgroup <- dlg_list(as.character(unique(metadata[,
  # group])), multiple = TRUE, title = 'Specify condition:')$res

  if (is.null(sample_names)) {
    sample_names <- dlg_list(names(metadata), multiple = FALSE, title = "Name sample as:")$res
  }

  # set to statistic pictures folder
  if (!example == TRUE) {
    if (!dir.exists("Statistics")) {
      dir.create("Statistics")
    }
    setwd("Statistics")

    if (!dir.exists("Heatmaps")) {
      dir.create("Heatmaps")
    }
    setwd("Heatmaps")
  }

  n[n == ""] <- NA
  mat <- n[, 6:(ncol(n) - 2)] # remove aditional information from the normalized quantification table
  mat <- apply(mat, MARGIN = 2, FUN = as.numeric)
  rownames(mat) <- n[, 1]

  # plot heatmap of metabolites per sample - named as 'sample' from
  # metadata
  mat_scaled <- scale(mat)
  colnames(mat_scaled) <- metadata$sample
  m <- n[, "Compound Name"]
  m[m == ""] <- NA
  rownames(mat_scaled) <- m

  for (i in seq_len(length(colors))) {
    ann <- data.frame(colors[[i]][[1]])
    colnames(ann) <- names(colors)[i]
    rownames(ann) <- metadata$sample
    ant <- list(colors[[i]][[2]])
    names(ant) <- names(colors)[i]

    if (".png" %in% pic_extension & !example == TRUE) {
      png(paste0(names(colors)[i], "_heatmap_scaled_geral.png"),
        units = "cm",
        width = 16, height = 16, res = 900, bg = "NA"
      )
      pheatmap(mat_scaled,
        cluster_rows = FALSE, annotation = ann, annotation_colors = ant,
        main = "Heatmap of samples by spectra\n", fontsize_col = 5, fontsize_row = 4,
        show_rownames = FALSE, border_color = "NA"
      )
      dev.off()
    }
    if (".tiff" %in% pic_extension & !example == TRUE) {
      tiff(paste0(names(colors)[i], "_heatmap_scaled_geral.tiff"),
        units = "cm",
        width = 16, height = 16, res = 900, bg = "NA"
      )
      pheatmap(mat_scaled,
        cluster_rows = FALSE, annotation = ann, annotation_colors = ant,
        main = "Heatmap of samples by spectra\n", fontsize_col = 5, fontsize_row = 4,
        show_rownames = FALSE, border_color = "NA"
      )
      dev.off()
    }
  }


  # plot heatmap of metabolites per sample - named as the user set
  mat_scaled <- scale(mat)
  colnames(mat_scaled) <- metadata[, sample_names]
  m <- n[, "Compound Name"]
  m[m == ""] <- NA
  rownames(mat_scaled) <- m

  for (i in seq_len(length(colors))) {
    if (".png" %in% pic_extension & !example == TRUE) {
      png(
        paste0(
          "named_", sample_names, "grouped_", names(colors)[i],
          "_heatmap_scaled_geral.png"
        ),
        units = "cm", width = 16, height = 16,
        res = 900, bg = "NA"
      )
      pheatmap(mat_scaled,
        cluster_rows = FALSE, main = "Heatmap of samples by spectra\n",
        fontsize_col = 5, fontsize_row = 4, show_rownames = FALSE, border_color = "NA"
      )
      dev.off()
    }
    if (".tiff" %in% pic_extension & !example == TRUE) {
      tiff(
        paste0(
          "named_", sample_names, "grouped_", names(colors)[i],
          "_heatmap_scaled_geral.tiff"
        ),
        units = "cm", width = 16, height = 16,
        res = 900, bg = "NA"
      )
      pheatmap(mat_scaled,
        cluster_rows = FALSE, main = "Heatmap of samples by spectra\n",
        fontsize_col = 5, fontsize_row = 4, show_rownames = FALSE, border_color = "NA"
      )
      dev.off()
    }
  }


  # only annotated metabolites per sample - samples named after 'sample'
  # from metadata
  if (!sum(is.na(n[, 3])) <= 0) {
    mat_ident <- mat[-which(is.na(n[, 3])), ]
  } else {
    mat_ident <- mat
  }
  mat_ident_scaled <- scale(mat_ident)
  colnames(mat_ident_scaled) <- metadata$sample
  rownames(mat_ident_scaled) <- n[-which(is.na(n[, 3])), 3]

  for (i in seq_len(length(colors))) {
    ann <- data.frame(colors[[i]][[1]])
    colnames(ann) <- names(colors)[i]
    rownames(ann) <- metadata[, "sample"]
    ant <- list(colors[[i]][[2]])
    names(ant) <- names(colors)[i]

    if (".png" %in% pic_extension & !example == TRUE) {
      png(paste0("heatmap_scaled_ident_", names(colors)[i], "_.png"),
        units = "cm",
        width = 16, height = 16, res = 900, bg = "NA"
      )
      pheatmap(mat_ident_scaled,
        cluster_rows = FALSE, main = "Heatmap of samples by spectra\n",
        fontsize_col = 5, annotation = ann, annotation_colors = ant,
        border_color = "NA", fontsize_row = 4
      )
      dev.off()
    }
    if (".tiff" %in% pic_extension & !example == TRUE) {
      tiff(paste0("heatmap_scaled_ident_", names(colors)[i], "_.tiff"),
        units = "cm", width = 16, height = 16, res = 900, bg = "NA"
      )
      pheatmap(mat_ident_scaled,
        cluster_rows = FALSE, main = "Heatmap of samples by spectra\n",
        fontsize_col = 5, annotation = ann, annotation_colors = ant,
        border_color = "NA", fontsize_row = 4
      )
      dev.off()
    }
  }

  # only annotated metabolites per sample - samples named after user set
  if (!sum(is.na(n[, 3])) <= 0) {
    mat_ident <- mat[-which(is.na(n[, 3])), ]
  } else {
    mat_ident <- mat
  }
  mat_ident_scaled <- scale(mat_ident)
  colnames(mat_ident_scaled) <- metadata[, sample_names]
  rownames(mat_ident_scaled) <- n[-which(is.na(n[, 3])), 3]

  for (i in seq_len(length(colors))) {
    if (".png" %in% pic_extension & !example == TRUE) {
      png(paste0(
        "named_", sample_names, "heatmap_scaled_ident_", names(colors)[i],
        "_.png"
      ), units = "cm", width = 16, height = 16, res = 900, bg = "NA")
      pheatmap(mat_ident_scaled,
        cluster_rows = FALSE, main = "Heatmap of samples by spectra\n",
        fontsize_col = 5, border_color = "NA", fontsize_row = 4
      )
      dev.off()
    }
    if (".tiff" %in% pic_extension & !example == TRUE) {
      tiff(
        paste0(
          "named_", sample_names, "heatmap_scaled_ident_", names(colors)[i],
          "_.tiff"
        ),
        units = "cm", width = 16, height = 16, res = 900,
        bg = "NA"
      )
      pheatmap(mat_ident_scaled,
        cluster_rows = FALSE, main = "Heatmap of samples by spectra\n",
        fontsize_col = 5, border_color = "NA", fontsize_row = 4
      )
      dev.off()
    }
  }

  # REPLICATE MEAN calculate mean of technical replicates
  if (is.null(replicate) & !example == TRUE) {
    replicate <- dlg_list(c(colnames(metadata), "No information"),
      multiple = FALSE,
      title = "Replicate data:"
    )$res
  }
  if (replicate == TRUE | replicate %in% colnames(metadata)) {
    nhmedia <- matrix(nrow = nrow(mat), ncol = length(unique(metadata[, replicate])))
    colnames(nhmedia) <- unique(metadata[, replicate])
    for (i in unique(metadata[, replicate])) {
      x <- grep(i, metadata[, replicate])
      for (ii in seq_len(nrow(mat))) {
        nhmedia[ii, i] <- sum(mat[ii, x]) / length(x)
      }
    }
    nhmedia_scaled <- scale(nhmedia) # scale

    # plot heatmaps for ident + non_ident metabolites (MEAN)
    if (".png" %in% pic_extension & !example == TRUE) {
      png("heatmap_repMean_scaled_geral.png",
        units = "cm", width = 16,
        height = 16, res = 900, bg = "NA"
      )
      pheatmap(nhmedia_scaled,
        cluster_rows = FALSE, main = "Heatmap of samples by spectra\n",
        fontsize_col = 5, border_color = "NA", fontsize_row = 4
      )
      dev.off()
    }
    if (".tiff" %in% pic_extension & !example == TRUE) {
      tiff("heatmap_repMean_scaled_geral.tiff",
        units = "cm", width = 16,
        height = 16, res = 900, bg = "NA"
      )
      pheatmap(nhmedia_scaled,
        cluster_rows = FALSE, main = "Heatmap of samples by spectra\n",
        fontsize_col = 5, border_color = "NA", fontsize_row = 4
      )
      dev.off()
    }

    # only annotated metabolites (MEAN)
    mat_ident <- mat[-which(is.na(n[, 3])), ]
    nhmedia_ident <- matrix(nrow = nrow(mat_ident), ncol = length(unique(metadata[
      ,
      replicate
    ])))
    colnames(nhmedia_ident) <- unique(metadata[, replicate])
    rownames(nhmedia_ident) <- n[-which(is.na(n[, 3])), 3]
    for (i in unique(metadata[, replicate])) {
      x <- grep(i, metadata[, replicate])
      if (length(x) > 1) {
        for (ii in seq_len(nrow(mat_ident))) {
          nhmedia_ident[ii, i] <- sum(mat_ident[ii, x]) / length(x)
        }
      } else {
        nhmedia_ident[ii, i] <- mat_ident[ii, x]
      }
    }
    nhmedia_scaled_ident <- scale(nhmedia_ident) # scale

    # plot heatmaps png
    if (".png" %in% pic_extension & !example == TRUE) {
      png("heatmap_repMean_scaled_ident_unique.png",
        units = "cm", width = 16,
        height = 16, res = 900, bg = "NA"
      )
      pheatmap(nhmedia_scaled_ident,
        cluster_rows = FALSE, main = "Heatmap of samples by spectra\n",
        fontsize_row = 4, fontsize_col = 5, border_color = "NA"
      )
      dev.off()
    }
    # tiff
    if (".tiff" %in% pic_extension & !example == TRUE) {
      tiff("heatmap_repMean_scaled_ident_unique.tiff",
        units = "cm", width = 16,
        height = 16, res = 900, bg = "NA"
      )
      pheatmap(nhmedia_scaled_ident,
        cluster_rows = FALSE, main = "Heatmap of samples by spectra\n",
        fontsize_row = 4, fontsize_col = 5, border_color = "NA"
      )
      dev.off()
    }
  }

  # back to main folder
  if (!example == TRUE) {
    setwd(myDir)
  }
}
