#' PCA_general
#'
#' This function plots PCA.
#' @export
#' @param myDir Path to the directory of work.
#' @param example Only for software testing. No pictures will be created.
#' @param metadata A matrix or data.frame with metadata information about samples. Include, at least 'sample' and 'file' columns with name of sample and its path, respectively. More information can be added in new columns, such as 'group', 'class', 'biorep' and 'tecrep'.
#' @param colors A list with colors generated from 'read_data()'
#' @param n A normalized matrix generated by 'PipMet::normalize()'
#' @param example Logical. If is example, pop-ups won't appear. Default to FALSE.
#' @param pic_extension Character. Pictures format to generate. Supported = '.tiff', '.png'. Default to c('.tiff', '.png').
#' @return None.
#' @importFrom grDevices dev.off pdf png tiff
#' @importFrom graphics boxplot grid legend par text
#' @importFrom stringr str_c
#' @importFrom methods as new
#' @importFrom stats cor sd t.test var prcomp na.omit
#' @importFrom utils menu read.csv select.list write.csv write.table
#' @import ggplot2
#' @importFrom ggrepel geom_text_repel
#' @examples
#' \donttest{
#' \dontrun{
#' load(system.file('extdata', 'n.RData', package = 'PipMet'))
#' load(system.file('extdata', 'colors.RData', package = 'PipMet'))
#' load(system.file('extdata', 'metadata.RData', package = 'PipMet'))
#' PCA_general(n, metadata, colors = colors, example = TRUE)
#' }
#'}

PCA_general <- function(n, metadata, myDir, colors, pic_extension = c(".tiff", ".png"), example = FALSE) {

    # --- 1. PREPARAÇÃO DA MATRIZ ---
    mat <- n[, 6:ncol(n)]
    mat <- apply(mat, MARGIN = 2, FUN = as.numeric)
    rownames(mat) <- n[, 1]

    if (!example == TRUE) {
        setwd(myDir)
        if (!dir.exists("PCA_general")) { dir.create("PCA_general") }
        setwd("PCA_general")
    }

    # --- 2. PCA GLOBAL (Sempre executa e guarda primeiro) ---
    message("Gerando PCA Global...")
    pc_global <- prcomp(t(na.omit(mat[, seq_len(nrow(metadata))])), center = TRUE)
    pcSum_global <- summary(pc_global)

    # Loop de plotagem para o GLOBAL
    for (i in seq_len(length(colors))) {
        col_list <- colors[[i]][[1]]
        
        if (".png" %in% pic_extension & !example == TRUE) {
            png(str_c("PCA_GLOBAL_", names(colors)[[i]], ".png"), units = "cm", width = 16, height = 16, res = 900)
            p <- ggplot(data = as.data.frame.array(pc_global$x), aes(x = pc_global$x[, 1], y = pc_global$x[, 2], color = col_list)) +
                 geom_point(size = 3) + stat_ellipse(geom = "polygon", aes(fill = col_list), alpha = 0.2) +
                 labs(title = "Global PCA", x = paste0("PC1 (", round(pcSum_global$importance[2,1]*100,1), "%)"), 
                      y = paste0("PC2 (", round(pcSum_global$importance[2,2]*100,1), "%)")) + theme_minimal()
            print(p); dev.off()
        }
        # Repetir para TIFF se necessário...
    }

    # --- 3. PCA DE SUBGRUPOS (Opcional e isolado) ---
    if (!example == TRUE) {
        
        quer_grupos <- askYesNo("Global PCA done. Would you like to generate PCA for SPECIFIC groups/conditions?")
        
        if (!is.na(quer_grupos) && quer_grupos == TRUE) {
            
            continuar <- TRUE
            while (continuar) {
                
                coluna <- svDialogs::dlg_list(names(metadata), title = "Select metadata column:")$res
                
                if (length(coluna) > 0) {
                    escolhidos <- svDialogs::dlg_list(as.character(unique(metadata[, coluna])), 
                                                    multiple = TRUE, title = "Select groups to compare:")$res
                    
                    if (length(escolhidos) >= 2) {
                        # Filtra apenas as amostras dos grupos selecionados
                        idx <- which(metadata[, coluna] %in% escolhidos)
                        
                        # NOVO cálculo de PCA apenas com estes dados
                        pc_sub <- prcomp(t(na.omit(mat[, idx])), center = TRUE)
                        pcSum_sub <- summary(pc_sub)
                        
                        # Criar subpasta para esta comparação
                        nome_pasta <- paste0("PCA_", coluna, "_", paste(escolhidos, collapse = "_"))
                        if (!dir.exists(nome_pasta)) { dir.create(nome_pasta) }
                        setwd(nome_pasta)

                        # Plotagem do SUBGRUPO
                        for (i in seq_len(length(colors))) {
                            cores_sub <- colors[[i]][[1]][idx]
                            
                            png(str_c("PCA_Subgrupo_", names(colors)[[i]], ".png"), units = "cm", width = 16, height = 16, res = 900)
                            p_sub <- ggplot(data = as.data.frame.array(pc_sub$x), 
                aes(x = pc_sub$x[, 1], y = pc_sub$x[, 2], color = cores_sub)) +
         geom_point(size = 3) + 
         stat_ellipse(geom = "polygon", aes(fill = cores_sub), alpha = 0.2) +
         labs(title = paste("PCA:", coluna), 
              subtitle = paste(escolhidos, collapse = " vs "),
              # Eixo X (já estava ok)
              x = paste0("PC1 (", round(pcSum_sub$importance[2,1]*100,1), "%)"),
              # Eixo Y (adicionado agora)
              y = paste0("PC2 (", round(pcSum_sub$importance[2,2]*100,1), "%)"),
              # Títulos das Legendas
              color = "Groups", 
              fill = "Groups") + 
         theme_minimal()
                            print(p_sub); dev.off()
                        }
                        setwd("..") # Volta para a pasta PCA_general
                    }
                }
                
                continuar <- askYesNo("Comparison finished. Would you like to do ANOTHER group comparison?")
                if (is.na(continuar)) continuar <- FALSE
            }
        }
    }

    if (!example == TRUE) { setwd(myDir) }
}