#' Statistics figures
#'
#' This function plots volcanos .
#' @export
#' @param myDir Path to the directory of work.
#' @param example Default to FALSE.
#' @param metadata A matrix or data.frame with metadata information about samples. Include, at least 'sample' and 'file' columns with name of sample and its path, respectively. More information can be added in new columns, such as 'group', 'class', 'biorep' and 'tecrep'.
#' @param n A normalized matrix generated by 'PipMet::normalize()'
#' @param pic_extension Character. Pictures format to generate. Supported = '.tiff', '.png'. Default to c('.tiff', '.png').
#' @return A directory for volcano plots.
#' @importFrom grDevices dev.off pdf png tiff
#' @importFrom graphics boxplot grid legend par text
#' @importFrom stats cor sd t.test var
#' @importFrom utils menu read.csv select.list write.csv write.table
#' @import ggplot2
#' @importFrom ggrepel geom_text_repel
#' @examples
#' \donttest{
#' \dontrun{
#' load(system.file("extdata", "n.RData", package = "PipMet"))
#' load(system.file("extdata", "metadata.RData", package = "PipMet"))
#' volcano_dir <- vol_lvl1(n, metadata, myDir = NULL, example = TRUE)
#' }
#' }
vol_lvl1 <- function(n, metadata, myDir, pic_extension = c(".tiff", ".png"),
                     example = FALSE) {
  mat <- n[, 6:ncol(n)] # remove aditional information from the normalized table of spectra
  mat <- apply(mat, MARGIN = 2, FUN = as.numeric)
  rownames(mat) <- n[, 1]
  mat[is.na(mat)] <- 0

  if (!example == TRUE) {
    setwd(myDir)
    if (!dir.exists("Statistics") == TRUE) {
      dir.create("Statistics")
    }
    setwd("Statistics")
    if (!dir.exists("Volcanos") == TRUE) {
      dir.create("Volcanos")
    }
    setwd("Volcanos")

    volDir <- getwd()
  }

  dlg_message("Volcano level one. Choose a condition to compare and two characteristics within that group. The resulting volcano will represent 'Condition: A X B'.")$res
  if (!example == TRUE) {
    x <- menu(names(metadata), graphics = TRUE, title = "Condition to compare:") # ask condition to compare from the metadata table
    opt <- select.list(as.character(unique(metadata[, as.integer(x)])),
      preselect = NULL,
      multiple = TRUE, title = "Select two characteristic to compare",
      graphics = TRUE
    ) # from that condition, which characteristics to compare
  } else {
    x <- 1
    opt <- c("Sugar", "Energy")
  }
  first <- grep(opt[1], metadata[, (as.integer(x))], fixed = TRUE)
  sec <- grep(opt[2], metadata[, (as.integer(x))], fixed = TRUE)

  # create folder for comparison
  if (!example == TRUE) {
    if (!dir.exists(paste0(opt[1], " X ", opt[2])) == TRUE) {
      dir.create(paste0(opt[1], " X ", opt[2]))
    }
    setwd(paste0(opt[1], " X ", opt[2]))
  }

  # calculate t test
  rawpvalue <- matrix(nrow = nrow(mat), ncol = 1)
  for (i in seq_len(nrow(mat))) {
    rawpvalue[[i]] <- t.test(as.numeric(mat[i, first]), as.numeric(mat[
      i,
      sec
    ]))$p.value
  }

  # calculates foldchange and plot histogram
  firstCond <- apply(mat[, first], 1, mean)
  secCond <- apply(mat[, sec], 1, mean)
  foldchange <- firstCond - secCond
  de <- as.data.frame(cbind(foldchange, rawpvalue))
  colnames(de) <- c("foldchange", "rawpvalue")
  for (i in seq_len(nrow(n))) {
    if (is.na(n[i, 3])) {
      de$spcId[i] <- n[i, 1]
    } else {
      de$spcId[i] <- n[i, 3]
    }
  } # add annotation if present

  # add identification for relative abundance (Unchanged, Up or Down)
  de$Relative_abundance <- "Unchanged"
  de$Relative_abundance[de$foldchange > 0.6 & de$rawpvalue < 0.05] <- "Up"
  de$Relative_abundance[de$foldchange < -0.6 & de$rawpvalue < 0.05] <- "Down"

  # plot volcanos without identification
  a <- ggplot(data = de, aes(x = foldchange, y = -log10(rawpvalue), col = de$Relative_abundance)) +
    geom_point() +
    theme_minimal() +
    geom_vline(
      xintercept = c(-0.6, 0.6),
      col = "red"
    ) +
    geom_hline(yintercept = -log10(0.05), col = "red") +
    ggtitle(label = paste0(
      opt[1],
      " X ", opt[2]
    )) +
    theme(rect = element_rect(fill = "transparent"), plot.title = element_text(
      hjust = 0.5,
      color = "black"
    )) +
    guides(color = guide_legend(title = "Relative abundance"))

  # png
  if (".png" %in% pic_extension & !example == TRUE) {
    png("volcano.png",
      units = "cm", width = 16, height = 16, res = 900,
      bg = "NA"
    )
    gridExtra::grid.arrange(a)
    dev.off()
  }
  # tiff
  if (".tiff" %in% pic_extension & !example == TRUE) {
    tiff("volcano.tiff",
      units = "cm", width = 16, height = 16, res = 900,
      bg = "NA"
    )
    gridExtra::grid.arrange(a)
    dev.off()
  }

  # plot volcanos with identification
  de$delabel <- NA
  de$delabel[de$Relative_abundance != "Unchanged"] <- de$spcId[de$Relative_abundance !=
    "Unchanged"]
  b <- ggplot(data = de, aes(
    x = foldchange, y = -log10(rawpvalue), col = de$Relative_abundance,
    label = de$delabel
  )) +
    geom_point() +
    ggtitle(label = paste0(
      opt[1],
      " X ", opt[2]
    )) +
    theme_minimal() +
    geom_vline(
      xintercept = c(-0.6, 0.6),
      col = "red"
    ) +
    geom_hline(yintercept = -log10(0.05), col = "red") +
    geom_text_repel() +
    theme(rect = element_rect(fill = "transparent"), plot.title = element_text(
      hjust = 0.5,
      color = "black"
    )) +
    xlab("Log2 Mean Fold Change") +
    ylab("-Log10 pValue") +
    guides(color = guide_legend(title = "Relative abundance"))

  # png
  if (".png" %in% pic_extension & !example == TRUE) {
    png("volcano_identified.png",
      units = "cm", width = 16, height = 16,
      res = 900, bg = "NA"
    )
    gridExtra::grid.arrange(b)
    dev.off()
  }
  # tiff
  if (".tiff" %in% pic_extension & !example == TRUE) {
    tiff("volcano_identified.tiff",
      units = "cm", width = 16, height = 16,
      res = 900, bg = "NA"
    )
    gridExtra::grid.arrange(b)
    dev.off()
  }

  if (!example == TRUE) {
    write.csv(de, file = "Significance_compounds_vol_lvl1.csv")

    # set to main folder
    setwd(myDir)

    # return results
    return(volDir)
  }
}
